python 3dar_interpolation_2.py ../images/image0.png ../images/image1.png ../images/image2.png ../output/out.png 7 11 1
python 3dar_interpolation_2.py ../images/image0.png ../images/image1.png ../images/image2.png ../output/out.png 7 13 1
python 3dar_interpolation_2.py ../images/image0.png ../images/image1.png ../images/image2.png ../output/out.png 7 15 1
python 3dar_interpolation_2.py ../images/image0.png ../images/image1.png ../images/image2.png ../output/out.png 7 17 1
python 3dar_interpolation_2.py ../images/image0.png ../images/image1.png ../images/image2.png ../output/out.png 7 19 1
python 3dar_interpolation_2.py ../images/image0.png ../images/image1.png ../images/image2.png ../output/out.png 7 21 1
python 3dar_interpolation_2.py ../images/image0.png ../images/image1.png ../images/image2.png ../output/out.png 7 23 1
python 3dar_interpolation_2.py ../images/image0.png ../images/image1.png ../images/image2.png ../output/out.png 7 25 1
python 3dar_interpolation_2.py ../images/image0.png ../images/image1.png ../images/image2.png ../output/out.png 7 27 1
python 3dar_interpolation_2.py ../images/image0.png ../images/image1.png ../images/image2.png ../output/out.png 7 29 1